### PR TITLE
Added simple author information below titles.

### PR DESCRIPTION
**Pull request by jeromekelleher**

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Not ready to merge, something's buggering up the image numbering...

**Comment by molpopgen** [comment]
Won't this also break other open PRs?  These notebooks aren't very merge-able.

**Comment by jeromekelleher** [comment]
I don't think so --- there's only one PR open, which just affects the Cython notebook, which I haven't touched.

**Comment by jeromekelleher** [comment]
OK fixed image renumbering issue (turns out nbconvert renumbers the images sometimes for the laugh, so you have to do a lot of ``git rm`` and ``git add`` ing), so merging this to see how it looks on the live site.

**Pull request merged**
