### PR TITLE
Start filling out "getting started"

### PR DESCRIPTION
**Pull request by hyanwong**
Some suggestions for better tree iteration examples welcome.

I think we should make an effort to link to the other tuts from this one. I've made a start, but more can be done

### CODE REVIEW

**Comment by hyanwong** [comment]
This is almost entirely filled out now @benjeffery. I have changed the example to one with a selective sweep - see what you think.I'm quite pleased: it introduces simplify, draw_svg, keep_intervals, ts.trees(), ts.sites(), ts.node(x) and a few objects, ts.variants(), and a few stats, including windowing, but doesn't feel *too* long (although it's on the upper end).

It's failing compilation because it's referring to some refs which are only present in the latest tskit version, but I can cull those out like I did for #66

**Comment by jeromekelleher** [comment]
I had a look through this just now with @hyanwong, and it's looking great!

**Comment by hyanwong** [comment]
I think this can be merged now - main things to do are the export section and to insert links and tidy up the "Key points covered above" section.

**Review by jeromekelleher — APPROVED** [review]

**Review by benjeffery — APPROVED** [review]
LGTM - I clicked all the links too.

**Pull request merged**
