### PR TITLE
edits to forward example (closes #29)

### LINKED ISSUE #29: Review completing forward simulations page
#28 ported the content from the msprime docs on completing forward sims, which should be rendered here: https://tskit-dev.github.io/tutorials/completing-forward-sims.html (assuming gh-pages gets around to deploying it)

@petrelharp, can you have a look through and see if you spot anything bad and open issues if you do, please? We might want to consider expanding to mention stuff like pyslim etc, but it's good to get the basic ideas across here.

### PR DESCRIPTION
**Pull request by petrelharp**
`keep_input_roots` made this simpler. I probably ought to still mention pyslim, though, to say that "this is how SLiM & pyslim work".

### CODE REVIEW

**Comment by jeromekelleher** [comment]
LGTM. Can we add pyslim to the intersphinx mapping in _config.yml?

**Comment by petrelharp** [comment]
Just did it! =)

**Comment by petrelharp** [comment]
(I'm pretty happy with how quick that was to do, btw - I built locally, found the intersphinx config, fixed things up, etc, no problems.)

**Comment by petrelharp** [comment]
Rebased.

**Review by jeromekelleher — APPROVED** [review]

**Comment by jeromekelleher** [comment]
Awesome, merging.

**Pull request merged**
