### PR TITLE
Update forward_sims.md

### PR DESCRIPTION
**Pull request by hyanwong**
Clarify that this tutorial is about the principles of using tskit to build your own forwards-in-time tree sequence recording simulator

### CODE REVIEW

**Comment by hyanwong** [comment]
> @hyanwong -- I see this was already merged, but please fix the error. It misrepresents what fwdpy11 is.

Sure, how to you want me to phrase it, @molpopgen ? I was going to put links in to the packages too (presumably to the GitHub repos?)

**Comment by molpopgen** [comment]
> Sure, how to you want me to phrase it, @molpopgen ? I was going to put links in to the packages too (presumably to the GitHub repos?)

I added a review comment -- it is a simulator, same a slim, not a library.

**Comment by molpopgen** [comment]
> presumably to the GitHub repos?

and/or pypi and/or manual?

**Comment by hyanwong** [comment]
> > Sure, how to you want me to phrase it, @molpopgen ? I was going to put links in to the packages too (presumably to the GitHub repos?)
> 
> I added a review comment -- it is a simulator, same a slim, not a library.

Sorry, I didn't see that.

**Comment by molpopgen** [comment]
> Should I just say: "forwards-in-time genetic simulators
> (such as SLiM and fwdpy11) and forwards-in-time simulation libraries (such as
> fwdpp)"?

Yes, this is correct.  Also, you should delete the reference to fwdpp as it implements its own version of a table collection/simplification and never uses tskit except for the C lib as a testing dependency.

I think I added the review comment post-merge, so I guess it got lost?

**Pull request merged**
