### PR TITLE
Rework the tute to showcase metadata

### PR DESCRIPTION
**Pull request by hyanwong**
And also how to edit each row (using metadata as an example), using the new tskit 0.4 accessors.

I also changed round the order so that we illustrate accessing columns as a big numpy array (which is a common thing to want to do) before accessing / writing to rows, as the logical flow worked better like that. The example for major edits showcases how to map mutations parsimoniously, rather than removing singletons, which is now done more easily using `delete_sites` (example also included).

To be merged after tskit 0.4 is released.

### CODE REVIEW

**Comment by hyanwong** [comment]
@LukeAndersonTrocme - you mentioned in https://github.com/tskit-dev/msprime/pull/1913#issuecomment-968323680 that metadata was a bit tricky to figure out. This change to the tutorials gives specific examples of how to add / edit tables, using the example of JSON metadata, although it doesn't talk much about how the schemas work (which is covered more in the [metadata documentation](https://tskit.dev/tskit/docs/latest/metadata.html) and the ["working with metadata" tute](https://tskit.dev/tutorials/metadata.html). If you have time, and think it would be helpful for others, do you want to read through it to see if it makes sense? The most relevant parts are the "Metadata" and "Minor edits" sections, both quite short.

**Comment by LukeAndersonTrocme** [comment]
The [metadata documentation](https://tskit.dev/tskit/docs/latest/metadata.html) is very well organized and clear. I appreciated the links to external sources to learn more about JSON for example. I also very much appreciated the extensive documentation about types and how to store them within the metadata field. 

This is a minor style suggestion, but I think the first couple paragraphs of the article could be rearranged? I like the first paragraph, but the second one I find jumps into the weeds a little early, I might suggest moving up the paragraphs describing why metadata is useful _"It is best practise to populate these fields if your files will be used by any third party, or if you wish to remember what they were some time after making the file! "_

The [tutorial](https://tskit.dev/tutorials/metadata.html) is excellent. There were a few bits a pieces of it that were a little confusing to me, but much of this confusion is likely due to the fact that I am relatively unfamiliar with python and JSON, which may not be the case for the average tskit user. 

A "live tweeting" of my read-through:
- toy example file ("data/metadata.trees") used in tutorial presumably comes with the tskit installation
- definitely appreciate showing the equivalent routes to access the information through `TreeSequence` or `TableCollection` I remember this being confusing to me. 
- "Reading metadata and schemas" specifically Schemas had me googling a bit to remind myself what we were talking about. Could be useful to add a sentence reminding the reader what a Schema is and why it can be useful.  
- Adding to this, the note about there being no schema came as a bit of a surprise to me, I thought "if schemas are not required then what's the point of including them?" 
- Great examples of basic and complex schemas. I wonder if all it takes is a link in the above sections to this little code block.
- `tables.individuals.add_row(0, metadata={"accession": "Bob1234", "pcr": True})` is a particularly enlightening line of code. This really brings the message home.
- On that note I really liked the examples that fail the validation!! very clear to me now. 
-  ah yes. The infamous `b` of the raw metadata `b'{"accession":"Bob1234","pcr":true}'` This is what was most confusing to me when I first encountered the metadata. I struggled a lot to figure out that this needed to be parsed. (note: the tutorial does clarify this very well 👍 )


Overall both the docs and tutorials were very clear, good section headers, excellent examples. I really appreciate having both simple and complex examples of metadata. The minor complaints I lay out above could likely all be solved with a few hyperlinks pointing to downstream sections of the text. Re-reading my comments now I realize that most if not all of the comments I made were addressed further down in the docs/tutorial.

I hope this rambling stream of thought was useful!

**Comment by hyanwong** [comment]
Really useful. Thanks @LukeAndersonTrocme

**Review by jeromekelleher — APPROVED** [review]
LGTM

**Comment by hyanwong** [comment]
Won't pass CI until tskit 0.4 docs are on stable.

**Comment by jeromekelleher** [comment]
Ready to merge?

**Comment by hyanwong** [comment]
Yep, merge it.

**Pull request merged**
