### PR TITLE
Suggested edits

### PR DESCRIPTION
**Pull request by gregorgorjanc**
Passed terminology_and_concepts.md and thought these edits might be useful.

My plan is to go over some/most of the tuts. Should I suggest edits one at a time or in a batch?

### CODE REVIEW

**Comment by benjeffery** [comment]
LGTM - needs a sqash and rebase before merge as the commit list has a merge commit in.

**Comment by gregorgorjanc** [comment]
@benjeffery I always struggle with `squash and rebase` - where can I get a dummy `do this after you have opened PR` help on doing this? THANKS!

**Comment by benjeffery** [comment]
> @benjeffery I always struggle with `squash and rebase` - where can I get a dummy `do this after you have opened PR` help on doing this? THANKS!

The workflow docs are here:
https://tskit.dev/tskit/docs/stable/development.html#git-workflow

I can fix up this PR if you like?

**Comment by petrelharp** [comment]
Also for "when rebasing goes wrong" see: https://popsim-consortium.github.io/stdpopsim-docs/stable/development.html#when-rebasing-goes-wrong

**Pull request closed without merging**
