### PR TITLE
Remove the code in the parallel example

### PR DESCRIPTION
**Pull request by hyanwong**
And set a random seed for replicability.

This should fix our compilation issues, I hope.

### CODE REVIEW

**Comment by jeromekelleher** [comment]
Hmm - I'd be tempted to just drop that "Working with threads" section actually. The LDCalculator is pretty much useless now as it can't handle multiple mutations (so most msprime simulations will fail), and the class itself is going to be deprecated as soon as we can get around to it https://github.com/tskit-dev/tskit/issues/1900

So, easiest to just delete this? We can come up with other, better examples of doing things in parallel and get rid of this large file clogging up the repo.

**Comment by hyanwong** [comment]
Yeah, happy to drop, or perhaps replace with an equivalent (e.g. calculating GNN in parallel, like we did in the Ancestry of Everyone paper?). But maybe worth merging this just so we have a record of what actually works? I could slim down the file easily enough by cutting the number of samples or the genome length.

**Comment by jeromekelleher** [comment]
The file is still a megabyte which is too big for git by rights. I'd just delete it and mark as a TODO.

**Comment by hyanwong** [comment]
Example deleted. This should be able to be merged now @jeromekelleher , to unblock the tutorials CI.

**Review by jeromekelleher — APPROVED** [review]
LGTM

Probably not worth expunging the 10MB trees file, but we should keep it in mind in the future if this repo is getting unwieldy

**Pull request merged**
