### PR TITLE
Add an intro to forward sims + a basic SLiM script

### PR DESCRIPTION
**Pull request by hyanwong**
For the forward simulation tutorials, it would be nice to be able to run SLiM on the command line. I don't know how we set up CI in this repo to install SLiM, or indeed if we want to (but I think we should). I find it helpful to know how to run SLiM from a python script as in the PR (which would of course allow analysis in a Jupyter notebook)

@petrelharp - there is a tutorial and a few vignettes in the pyslim repo. Do we want to jupyter-book-ify any and move them into the general "tutorials" repo? I can help with this.

### CODE REVIEW

**Review by benjeffery — APPROVED** [review]
LGTM, I've added a change to install the tskit beta to get this to pass CI. Lets see if it works or if we need a separate PR.

**Comment by hyanwong** [comment]
It won't pass until we can install SLiM on CI (which presumably means changing the setup to use conda). So I should have marked this as a draft, for comments, sorry @benjeffery !

**Comment by hyanwong** [comment]
Also we'd need a version of SLiM / payslip that works with tskit 0.4. That might be a day or two.

**Comment by benjeffery** [comment]
Ah ok! I think I'll do a separate PR for 0.4.0 then. Thanks!

**Comment by hyanwong** [comment]
We decided that we wouldn't put slim code into the tskit tutorials.

**Pull request closed without merging**
