### PR TITLE
What is sections

### PR DESCRIPTION
**Pull request by hyanwong**
By breaking the early content into named sections, we can link to a simple explanation of "local trees".

I took the mention of ARG out of the `sec_what_is_genealogical_network` section as it it mentioned lower down, at the top of the `sec_what_is_ancestry` section.

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM - did we stop using that .trees file at some point?

**Comment by hyanwong** [comment]
>  did we stop using that .trees file at some point?

No, I hope this PR doesn't delete it, just updates it to a more recent format so that the time_units is set.

**Comment by jeromekelleher** [comment]
Right sorry, didn't see that it was an update rather than deletion

**Comment by hyanwong** [comment]
> Right sorry, didn't see that it was an update rather than deletion

No problem. Good to check, thanks.

**Pull request merged**
